### ISSUE TITLE
Function never returns None

### ISSUE THREAD

**Issue by sbaer** [mcneel/rhinopython101manual#1]
Page 4

``` python
somenumber = rs.GetReal("Line length")
line = rs.AddLine([0,0,0], [somenumber,0,0])
if (line==None):
    print "Something went wrong"
else:
    print "Line curve inserted"
```

The AddLine function will never return None since it now throws an exception when you provide bad input. We might want to rewrite this to something like

``` python
somenumber = rs.GetReal("Line length")
line = rs.AddLine([0,0,0], [somenumber,0,0])
print "Line curve inserted with id", line
```

**Comment by SJET** [comment]
Done.

---

**_Skylar Tibbits_
TED Fellow 2011
www.sjet.us http://www.sjet.us/

**Comment by sbaer** [comment]
You can just click the "Close Issue" button on the web page to move this from an open bug to closed

**Comment by sbaer** [comment]
I'm testing to see what github does when I reply to one of these emails. 
Please ignore;)

-----Original Message-----
