### ISSUE TITLE
The Skin Image

### ISSUE THREAD

**Issue by sbaer** [mcneel/rhinopython101manual#3]
Section 3.4 (page13)

The image shows left mouse click as LoadScript and right mouse click as RunScript.

LoadScript is not used in python since there is no need for it.  RunScript should be replaced with RunPythonScript. We may some day figure out how to differentiate between python and rhinoscript in the RunScript command, but for now we can't and have to use RunPythonScript instead.

**Comment by SJET** [comment]
Done.

Skylar

---

**_Skylar Tibbits_
TED Fellow 2011
www.sjet.us http://www.sjet.us/
