### ISSUE TITLE
Script Fix

### ISSUE THREAD

**Issue by sbaer** [mcneel/rhinopython101manual#4]
Section 4.4.1

**line 3**
The script at the beginning of this section will not run. The comment on line 3 needs to start with a # character

**line 5**
rs.GetObject call will not work the way it is being called. It can either be called as
strObjectId = rs.GetObject("Select an object to rename", 0, False, True)
or
strObjectId = rs.GetObject("Select an object to rename", select=True)

**line 9**
string concatenation does not use the '&' character and should be replaced by the '+' character

Here's my rewrite

``` python
import rhinoscriptsyntax as rs
import time

#This script will rename an object using the current system time
strObjectID = rs.GetObject("Select an object to rename", select=True)
if strObjectID:
    strNewName = "Time: " + str(time.localtime())
    rs.ObjectName(strObjectID, strNewName)
```

Some other text in this section refers to this script and also needs updating

**Comment by SJET** [comment]
Fixed
